version: '3.1'
services:
  mongo:
    image: dolittle/mongodb
    hostname: mongo
    volumes:
      - ${PWD}/data:/data
    ports:
      - 27017:27017
    logging:
      driver: none

  runtime:
    image: dolittle/runtime:5.3.0-turbo.6
    volumes:
      - ${PWD}/.dolittle/resources.json:/app/.dolittle/resources.json
      - ${PWD}/.dolittle/tenants.json:/app/.dolittle/tenants.json
      - ${PWD}/appsettings.json:/app/appsettings.json
    ports:
      - 9700:9700
      - 50052:50052
      - 50053:50053
