name: Runtime

on:
  push:
    branches:
    - '**'

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release
  
  build-prod-docker-image:
    name: Build Production Docker Image
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Production Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        context: .
        file: ./Docker/Production/Dockerfile
  
  build-dev-docker-image:
    name: Build Development Docker Image
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Development Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        context: .
        file: ./Docker/Development/Dockerfile